#!/bin/bash

/opt/access2google/pendingRecord.py && #copies Access record to clipboard 

xclip -out > /tmp/accessRecord.txt && /opt/access2google/new_lender2illsheet.py | xclip -i -selection clipboard 

/opt/access2google/autotab_switcher.py 
